[library]
version = "0.5.2"
browse_url = "https://github.com/Rafostar/clapper/"
repository_url = "https://github.com/Rafostar/clapper.git"
website_url = "https://rafostar.github.io/clapper/"
docs_url = "https://rafostar.github.io/clapper/doc/clapper-gtk/"
authors = "Rafał Dzięgiel"
logo_url = "clapper-logo.svg"
license = "LGPL-2.1-or-later"
description = "Clapper GTK integration library"
devhelp = true
search_index = true

dependencies = ["Clapper-0.0", "Gtk-4.0"]

  [dependencies."Clapper-0.0"]
  name = "Clapper"
  description = "Clapper playback library"
  docs_url = "https://rafostar.github.io/clapper/doc/clapper/"

  [dependencies."Gtk-4.0"]
  name = "Gtk"
  description = "The GTK toolkit"
  docs_url = "https://docs.gtk.org/gtk4/"

related = ["GLib-2.0", "GObject-2.0", "Gst-1.0"]

  [related."GLib-2.0"]
  name = "GLib"
  description = "A general-purpose, portable utility library"
  docs_url = "https://docs.gtk.org/glib/"

  [related."GObject-2.0"]
  name = "GObject"
  description = "The base type system library"
  docs_url = "https://docs.gtk.org/gobject/"

  [related."Gst-1.0"]
  name = "Gst"
  description = "GStreamer core library"
  docs_url = "https://gstreamer.freedesktop.org/documentation/gstreamer/gi-index.html"

[theme]
name = "basic"
show_index_summary = true
show_class_hierarchy = true

[source-location]
base_url = "https://github.com/Rafostar/clapper/tree/master/"

[extra]
# The same order will be used when generating the index
content_files = [
]
content_images = [
  "images/clapper-logo.svg",
]
urlmap_file = "urlmap.js"
